### ISSUE TITLE
Benefits over a MediatR behavior

### ISSUE THREAD

**Issue by ffMathy** [f1ana/Elastic.Apm.MediatR#1]
What are the benefits of the diagnostic approach instead of defining a MediatR behavior that will create the spans instead?

**Comment by f1ana** [comment]
Please see the readme for this repo- it does define a MediatR behavior.

**Comment by ffMathy** [comment]
It doesn't though. Where do you see a reference to a behavior? 😅

**Comment by f1ana** [comment]
![image](https://user-images.githubusercontent.com/984790/159724356-c8db2f20-e28d-4ac9-9aa7-ad8491df3504.png)
